import {Command, Args, Flags} from '@oclif/core'
import {appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs'
import {homedir} from 'node:os'
import {basename, dirname, join} from 'node:path'

type Shell = 'zsh' | 'bash' | 'fish'

const SUPPORTED_SHELLS: readonly Shell[] = ['zsh', 'bash', 'fish'] as const

/**
 * 현재 셸을 process.env.SHELL 에서 감지한다. 감지 실패 시 null 반환.
 */
export function detectShell(): Shell | null {
  const shellEnv = process.env.SHELL ?? ''
  const shellName = basename(shellEnv).toLowerCase()
  if (shellName.includes('zsh')) return 'zsh'
  if (shellName.includes('bash')) return 'bash'
  if (shellName.includes('fish')) return 'fish'
  return null
}

/**
 * zsh completion 스크립트 본문을 생성한다.
 * compdef 기반의 단순 completion (subcommand/flag 후보 제공).
 */
export function buildZshScript(bin: string): string {
  return `#compdef ${bin}
# ${bin} zsh completion script
# Auto-generated by '${bin} completion install zsh'

_${bin}() {
  local -a commands
  local cur="\${words[CURRENT]}"

  # Top-level commands → '${bin} --help' 의 출력 일부를 기반으로 한 힌트
  commands=(
    'auth:인증 관리'
    'config:설정 관리'
    'plugin:플러그인 관리'
    'completion:셸 자동완성'
    'build:매니페스트로부터 명령 생성'
    'doctor:시스템 상태 확인'
    'init:프로젝트 초기화'
    'help:도움말 출력'
    'version:버전 출력'
  )

  if (( CURRENT == 2 )); then
    _describe 'command' commands
  else
    # 2단계 이상은 oclif 가 직접 --help 하도록 완화 fallback
    _files
  fi
}

compdef _${bin} ${bin}
`
}

/**
 * bash completion 스크립트 본문을 생성한다.
 * complete -F 기반.
 */
export function buildBashScript(bin: string): string {
  // bash 함수명에 '-' 가 있으면 invalid → '_' 로 치환
  const fn = `_${bin.replace(/[^A-Za-z0-9_]/g, '_')}_completion`
  return `# ${bin} bash completion script
# Auto-generated by '${bin} completion install bash'
# Source this file from your ~/.bashrc:
#   source ~/.${bin}-completion.bash
# Or place it in /etc/bash_completion.d/${bin}

${fn}() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"

  local cmds="auth config plugin completion build doctor init help version"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${cmds}" -- "\${cur}") )
    return 0
  fi

  # Fallback: 파일명 보완
  COMPREPLY=( $(compgen -f -- "\${cur}") )
  return 0
}

complete -F ${fn} ${bin}
`
}

/**
 * fish completion 스크립트 본문을 생성한다.
 */
export function buildFishScript(bin: string): string {
  return `# ${bin} fish completion script
# Auto-generated by '${bin} completion install fish'
# Place this file at: ~/.config/fish/completions/${bin}.fish

complete -c ${bin} -f
complete -c ${bin} -n '__fish_use_subcommand' -a 'auth' -d '인증 관리'
complete -c ${bin} -n '__fish_use_subcommand' -a 'config' -d '설정 관리'
complete -c ${bin} -n '__fish_use_subcommand' -a 'plugin' -d '플러그인 관리'
complete -c ${bin} -n '__fish_use_subcommand' -a 'completion' -d '셸 자동완성'
complete -c ${bin} -n '__fish_use_subcommand' -a 'build' -d '매니페스트로부터 명령 생성'
complete -c ${bin} -n '__fish_use_subcommand' -a 'doctor' -d '시스템 상태 확인'
complete -c ${bin} -n '__fish_use_subcommand' -a 'init' -d '프로젝트 초기화'
complete -c ${bin} -n '__fish_use_subcommand' -a 'help' -d '도움말 출력'
complete -c ${bin} -n '__fish_use_subcommand' -a 'version' -d '버전 출력'
`
}

/**
 * 셸별 install instruction (사람이 읽는 안내 문구) 를 생성한다.
 * --apply 가 false 일 때는 이 문구만 출력.
 */
function buildInstructions(shell: Shell, bin: string, scriptPath: string, rcSnippet: string): string[] {
  if (shell === 'zsh') {
    return [
      `[zsh] ${bin} 자동완성 설치`,
      ``,
      `1. 다음 디렉터리를 만들고 completion 파일을 저장하세요:`,
      `   mkdir -p ${dirname(scriptPath)}`,
      `   ${bin} completion install zsh --apply  # 또는 아래 스크립트를 직접 ${scriptPath} 에 저장`,
      ``,
      `2. ~/.zshrc 에 다음을 추가하세요:`,
      ``,
      ...rcSnippet.split('\n').map(l => `     ${l}`),
      ``,
      `3. 새 셸을 열거나 'source ~/.zshrc' 를 실행하세요.`,
    ]
  }
  if (shell === 'bash') {
    return [
      `[bash] ${bin} 자동완성 설치`,
      ``,
      `1. completion 스크립트를 저장하세요:`,
      `   ${bin} completion install bash --apply  # 또는 아래 스크립트를 ${scriptPath} 에 직접 저장`,
      ``,
      `2. ~/.bashrc (또는 시스템 전역 /etc/bash_completion.d/${bin}) 에 다음을 추가하세요:`,
      ``,
      ...rcSnippet.split('\n').map(l => `     ${l}`),
      ``,
      `3. 새 셸을 열거나 'source ~/.bashrc' 를 실행하세요.`,
    ]
  }
  return [
    `[fish] ${bin} 자동완성 설치`,
    ``,
    `1. fish completion 표준 위치에 저장하면 자동으로 로드됩니다:`,
    `   ${bin} completion install fish --apply  # 또는 아래 스크립트를 ${scriptPath} 에 저장`,
    ``,
    `2. fish 는 ~/.config/fish/completions/*.fish 를 자동 로드하므로 추가 설정이 불필요합니다.`,
  ]
}

/**
 * 셸별 (스크립트 경로, completion 스크립트, rc snippet) 을 반환한다.
 */
function buildPlan(shell: Shell, bin: string): {
  scriptPath: string
  script: string
  rcPath: string | null
  rcSnippet: string
} {
  const home = homedir()
  if (shell === 'zsh') {
    const scriptPath = join(home, '.zfunc', `_${bin}`)
    const script = buildZshScript(bin)
    const rcSnippet = [
      `# >>> ${bin} completion >>>`,
      `fpath=(${join('~', '.zfunc')} $fpath)`,
      `autoload -Uz compinit && compinit`,
      `# <<< ${bin} completion <<<`,
    ].join('\n')
    return {scriptPath, script, rcPath: join(home, '.zshrc'), rcSnippet}
  }
  if (shell === 'bash') {
    const scriptPath = join(home, `.${bin}-completion.bash`)
    const script = buildBashScript(bin)
    const rcSnippet = [
      `# >>> ${bin} completion >>>`,
      `[ -r ${scriptPath.replace(home, '~')} ] && source ${scriptPath.replace(home, '~')}`,
      `# <<< ${bin} completion <<<`,
    ].join('\n')
    return {scriptPath, script, rcPath: join(home, '.bashrc'), rcSnippet}
  }
  // fish
  const scriptPath = join(home, '.config', 'fish', 'completions', `${bin}.fish`)
  const script = buildFishScript(bin)
  return {scriptPath, script, rcPath: null, rcSnippet: ''}
}

export default class CompletionInstall extends Command {
  static override description = '셸 자동완성 설치 (zsh/bash/fish)'

  static override examples = [
    '<%= config.bin %> completion install',
    '<%= config.bin %> completion install zsh',
    '<%= config.bin %> completion install bash --dry-run',
    '<%= config.bin %> completion install fish --apply',
  ]

  static override args = {
    shell: Args.string({
      required: false,
      description: '셸 종류 (zsh/bash/fish). 생략 시 $SHELL 로 자동 감지.',
    }),
  }

  static override flags = {
    apply: Flags.boolean({
      description: 'completion 스크립트를 실제 파일에 기록하고 ~/.shellrc 에 source 라인을 추가합니다 (기본은 안내만)',
      default: false,
    }),
    'dry-run': Flags.boolean({
      description: '--apply 와 함께 사용 시, 실제로 파일을 변경하지 않고 변경 예정 파일/내용만 출력합니다',
      default: false,
    }),
  }

  async run(): Promise<void> {
    const {args, flags} = await this.parse(CompletionInstall)

    // 1) 셸 결정 (인자 우선, 없으면 자동 감지, 그래도 없으면 zsh default + 안내)
    const requested = (args.shell ?? '').toLowerCase()
    let shell: Shell
    if (requested) {
      if (!SUPPORTED_SHELLS.includes(requested as Shell)) {
        this.error(`지원하지 않는 셸: "${requested}". 지원: ${SUPPORTED_SHELLS.join(', ')}`, {exit: 1})
      }
      shell = requested as Shell
    } else {
      const detected = detectShell()
      if (detected) {
        shell = detected
        this.logToStderr(`(SHELL 환경변수로 ${shell} 감지)`)
      } else {
        shell = 'zsh'
        this.logToStderr(`(셸을 감지하지 못했습니다. 기본값 zsh 를 사용합니다. 명시적으로 'completion install bash' 등을 실행하세요.)`)
      }
    }

    const bin = this.config.bin
    const plan = buildPlan(shell, bin)
    const dryRun = flags['dry-run']
    const apply = flags.apply

    // 2) 안내 문구를 stdout 에 출력 (테스트 검증 대상)
    const instructions = buildInstructions(shell, bin, plan.scriptPath, plan.rcSnippet)
    for (const line of instructions) this.log(line)

    // 3) completion 스크립트 본문도 함께 출력 (사용자가 직접 저장할 수 있도록)
    this.log('')
    this.log(`--- ${bin} ${shell} completion 스크립트 ---`)
    this.log(plan.script)
    this.log(`--- 스크립트 끝 ---`)

    if (!apply) {
      this.log('')
      this.log(`(파일을 직접 변경하려면 '--apply' 플래그를 사용하세요. dry-run 으로 변경 예정만 보려면 '--apply --dry-run')`)
      return
    }

    // 4) --apply 처리
    this.logToStderr('')
    this.logToStderr(`[apply] ${shell} completion 설치를 진행합니다${dryRun ? ' (dry-run)' : ''}...`)

    // 4a) 스크립트 파일 작성
    const scriptDir = dirname(plan.scriptPath)
    if (dryRun) {
      this.logToStderr(`  [dry-run] mkdir -p ${scriptDir}`)
      this.logToStderr(`  [dry-run] write ${plan.scriptPath} (${plan.script.length} bytes)`)
    } else {
      mkdirSync(scriptDir, {recursive: true})
      writeFileSync(plan.scriptPath, plan.script, 'utf8')
      this.logToStderr(`  ✓ ${plan.scriptPath} 작성 완료`)
    }

    // 4b) rc 파일에 snippet 추가 (이미 있으면 skip)
    if (plan.rcPath && plan.rcSnippet) {
      const marker = `# >>> ${bin} completion >>>`
      const existing = existsSync(plan.rcPath) ? readFileSync(plan.rcPath, 'utf8') : ''
      if (existing.includes(marker)) {
        this.logToStderr(`  ✓ ${plan.rcPath} 에 이미 ${bin} completion snippet 이 있습니다. 건너뜁니다.`)
      } else if (dryRun) {
        this.logToStderr(`  [dry-run] append to ${plan.rcPath}:`)
        for (const l of plan.rcSnippet.split('\n')) this.logToStderr(`    ${l}`)
      } else {
        const prefix = existing.length > 0 && !existing.endsWith('\n') ? '\n' : ''
        appendFileSync(plan.rcPath, `${prefix}\n${plan.rcSnippet}\n`, 'utf8')
        this.logToStderr(`  ✓ ${plan.rcPath} 에 source snippet 추가 완료`)
      }
    }

    this.logToStderr('')
    this.logToStderr(`완료! 새 셸을 열거나 다음을 실행하세요:`)
    if (shell === 'zsh') this.logToStderr(`  source ~/.zshrc`)
    else if (shell === 'bash') this.logToStderr(`  source ~/.bashrc`)
    else this.logToStderr(`  exec fish`)
  }
}
